config/routes.rb
Rails.application.routes.draw do
  root                  'static_pages#home'
  get   'about'     =>  'static_pages#about'
  get   'research'  =>  'static_pages#research'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a full title for each page.
  def full_title(page_title = '')
    base_title = "BLAM\'s Series of Tubes"
    if page_title.empty?
      base_title
    else
      base_title + " | " + page_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <nav>
      <ul>
        <li><%= mail_to "brian.joseth.lambert@gmail.com", "Email", encode: "hex"   %></li>
        <li><%= link_to "Github",   'https://github.com/keldonia'   %></li>
        <li><%= link_to "Facebook", 'https://www.facebook.com/brian.lambert.9041'   %></li>
        <li><%= link_to "LinkedIn", 'https://www.linkedin.com/pub/brian-lambert/35/135/879'   %></li>
      </ul>
    </nav>
  </div>
</foot>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top'>
  <div class="container">
  <%= link_to "BLAM's Series of Tubes", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "About",  about_path %></li>
        <li><%= link_to "Research", research_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About BLAM') %>
<div class="row">
  <section class="col-md-3">
    <br>
    <h2>Brian Lambert</h2>
    <hr>
    <section class="picture_left img-rounded">
    <%= image_tag("personal1.png", :class => "img-rounded") %>
    </section>
  </section>
  <section class="col-md-9">
    <div class="home-text">
      <br>
      <br>
      <br>
      <p>I grew as an Army brat, meaning I was lucky enough to have lived in a variety of places, including Germany and Texas twice, Colorado, New York, Wisconsin, Minnesota, California, and most recently Tucson. Growing up in all these places allowed me to experience a variety of cultures and peoples.  In this time I enjoyed skiing, hiking, and of course experiencing other cultures and their cuisines. One of my most memorable experiences was hiking the Cinque Terre, on the Italian Riviera, with my parents and friends, when a huge rainstorm came forcing us to rush to the next town, where we were able to dry out next to a huge fireplace and have some of the best Pesto Genovese I have ever had.</p>
      <p>I studied economics and political science at Carleton College.  While in college, I participated in several clubs and activities, most prominently the Men’s Rugby Football Club.  In terms of academics my focus was economics and political science, with a semester spent studying abroad at Cambridge University in the UK.</p>
      <p>Upon graduation, I worked on a couple financial technology startups, though at the time I was focused more on the non-technical aspects of the project.  I returned to academia to pursue a graduate degree in political science at the University of Arizona, before deciding to depart with a master’s degree in May  2015.  I am currently spending my time tutoring students and learning how to code.</p>
    </div>
  </section>
</div>

app/views/static_pages/home.html.erb
<div class="row">
  <section class="col-md-9">
    <div class="home-text">
      <br>
      <h2>Welcome</h2>
      <p>The world is undergoing yet another revolution as our lives and decision making become increasingly defined by quantization and reliance on technology. This shift has elevated the necessity of coding, such that this world can be shaped for the benefit of all. Yet, beyond superlatives, coding is something that I find to be an increasingly important, and enjoyable, part of our lives.</p>

      <p>I am currently working on a project to bring more readily available information and understanding to entrepreneurs and businesses about payments technologies. This project seeks to provide the financial and integration information needed by entrepreneurs and businesses about online market platforms and payment systems – including alternative forms of payments beyond credit cards. My vision is for this project to provide the clearest and most accessible information on payments.</p>
      <br>
      <h4>Other concepts I am interested in pursuing:</h4>
      <ul>
        <li>A payments platform allowing customers to make in-aisle purchases, and avoid the checkout line</li>
        <li>A financial management application to better enable students and young professionals to improve their finances and credit</li>
        <li>A historically based multiplayer HTML5 strategy, allowing players to guide the destiny of their nations</li>
        <li>An application to make learning more accessible to broader segments of the population through gamification and multimedia</li>
        <li>An employment marketplace designed to aid recent and soon-to-be college graduates match with prospective employers</li>
        <li>An app to train users how to write better</li>
        <li>A framework for medical billing to make it more accurate and timely billing</li>
      </ul>
    </div>
  </section>
  <section class="col-md-3">
    <section class="picture_right img-rounded">
      <%= image_tag("lambert_brian.jpg", :class => "img-rounded, img-responsive") %>
    </section>
  </section>
</div>

app/views/static_pages/research.html.erb
<% provide(:title, 'Research') %>
<div class="row">
  <section class="col-md-3">
    <br>
    <h2>Research</h2>
    <hr>
    <section class="picture_left img-rounded">
    <%= image_tag("sustainability.png", :class => "img-rounded img-responsive") %>
    </section>
  </section>
  <section class="col-md-9">
    <div class="home-text">
      <br>
      <br>
      <p>While attending graduate school, I presented at several conferences and hosted a panel. My research primarily focused on sustainability and natural resources, though I did also do some research on gender and the social welfare state and terrorism. It was the focus on war and conflict that would eventually lead me to leaving my program.</p>

      <br>
      <h4>Topics I have researched, and some results:</h4>
      <ul>
        <li>The effect of the democratic process on environmental sustainability at the nation state level. I found that democratic societies were indeed more sustainable than other forms of government, though autocracies were more sustainable than anocracies (neither democracies nor autocracies).</li>
        <li>The effect of different types of natural resources the type of government of a country. I found that resources requiring greater internal investment in the nation are less susceptible to rent seeking behavior, increasing the likelihood of democratic governance.</li>
        <li>The effect of different types of natural resources on the onset of civil war. I found contrary to previous expectations, purer natural resources lead to decreased levels of conflict, due to increased military and security apparatus funding.</li>
        <li>The neighborhood effect on terrorism, ie how does the state capacity of neighboring countries effect the likelihood of terrorism in a country. In this paper, I found that terrorism is increased in countries bordered by less stable states. </li>
        <li>The role of the social welfare state and equitable outcomes for women. Intriguingly, in this paper I found that liberal democracies, with smaller levels of social welfare, increased women's performance and attainment in the workplace.</li>
      </ul>
      <h6>If you would like more information about any of these projects please feel free to send me an email.</h4>
    </div>
  </section>
</div>